### ISSUE TITLE
User can see their car. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Design a basic layout with CSS for the car.
- [x] Design a basic layout for the road.
- [x] If car is visible, proceed to next step.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
