### ISSUE TITLE
User can turn their car. 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Utilize JS DOM manipulation to adjust CSS properties of the car img, allowing the user to turn their car. 
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
